name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy=1.23.1
  - pandas=2.2.3
  - matplotlib=3.7.0
  - opencv
  - mediapipe
  - tensorflow=2.12.0
  - pip:
      - streamlit==1.40.0
      - gtts
